Traceback (most recent call last):
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from time import strftime,gmtime
with open("_config.yml","rt") as yaml:
  content=yaml.read()
date=strftime("%d/%m/%Y",gmtime())
newcontent=content[:174]+new+content[184:]
from shutil import copyfile
copyfile("_config.yml",f"retired/config{strftime('%d%m%Y',gmtime())}.yml")
with open("_config.yml","wt") as yaml:
  yaml.write(newcontent)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      3[0m   content[38;5;241m=[39myaml[38;5;241m.[39mread()
[1;32m      4[0m date[38;5;241m=[39mstrftime([38;5;124m"[39m[38;5;132;01m%d[39;00m[38;5;124m/[39m[38;5;124m%[39m[38;5;124mm/[39m[38;5;124m%[39m[38;5;124mY[39m[38;5;124m"[39m,gmtime())
[0;32m----> 5[0m newcontent[38;5;241m=[39mcontent[:[38;5;241m174[39m][38;5;241m+[39m[43mnew[49m[38;5;241m+[39mcontent[[38;5;241m184[39m:]
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mshutil[39;00m [38;5;28;01mimport[39;00m copyfile
[1;32m      7[0m copyfile([38;5;124m"[39m[38;5;124m_config.yml[39m[38;5;124m"[39m,[38;5;124mf[39m[38;5;124m"[39m[38;5;124mretired/config[39m[38;5;132;01m{[39;00mstrftime([38;5;124m'[39m[38;5;132;01m%d[39;00m[38;5;124m%[39m[38;5;124mm[39m[38;5;124m%[39m[38;5;124mY[39m[38;5;124m'[39m,gmtime())[38;5;132;01m}[39;00m[38;5;124m.yml[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'new' is not defined

